WIDTH, HEIGHT = 800, 600

CURRENT_BUTTON = None
CURRENT_COLOR = [0,0,0,0]
CURRENT_THICKNESS = 1 # 1=fino, 2=médio, 3=GROSSO

CANVAS_WIDTH = 800
CANVAS_HEIGHT = 510
CURRENT_ROW_MOUSE_ON = 0
CURRENT_COL_MOUSE_ON = 0

SHAPE_START = None